### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by nk9**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

When running the project from a fresh download, there are a number of compiler warnings which I have fixed.

### CODE REVIEW

**Review by michaelkirk — COMMENTED** [review]
Can you verify when these were introduced and that the corresponding non version of geo-types makes sense with this change?

**Comment by nk9** [comment]
- `Coordinate` to `Coord` was introduced in [geo_types 0.7.8](https://github.com/georust/geo/releases/tag/geo-types-0.7.8)
- `points_iter()` was marked as deprecated on 4 Jan 2022, with a [release it looks like of 0.7.13](https://github.com/georust/geo/releases/tag/geo-types-0.7.13)
- The two unused imports appear to have been added in [this commit](https://github.com/georust/geojson/commit/4cd8882d0b75ab646644a66f7a835b118a8d020c), and it looks like they were never actually needed.

I'm not sure what you mean about the "non version" of geo-types? I could easily have my setup wrong, not looking to create work for you. If I've overlooked a contribution guide, or left steps out, please let me know!

**Comment by michaelkirk** [comment]
sorry, "non" version was an autocorrect.

Can you please bump the min version of geo types in Cargo.toml to 0.7.8?

**Comment by nk9** [comment]
Sure, all done!

**Review by michaelkirk — APPROVED** [review]

**Comment by michaelkirk** [comment]
Thanks!

**Pull request merged**
