### PR TITLE
Added derive_more for Geojson allowing more features easier

### PR DESCRIPTION
**Pull request by rory**
added a few more ways convert to/from Geojson objects

### CODE REVIEW

**Comment by urschrei** [comment]
A couple of questions:
1. Does this just only enable From for the three types you removed the impls for, or are there more?
2. If we only require the From magic, can we tweak the features in Cargo.toml to try to reduce the compile times? I think syn is the heavy one, and we already depend on it, but we may as well try to be judicious.

**Comment by rory** [comment]
> Does this just only enable From for the three types you removed the impls for, or are there more?

It also added `.try_into` for the enum variants. The doctest show this by converting a `GeoJson` to a `Result<Feature, _>`

> If we only require the From magic, can we tweak the features in Cargo.toml to try to reduce the compile times? I think syn is the heavy one, and we already depend on it, but we may as well try to be judicious.

I don't know much about that area, but I will investigate.

**Comment by urschrei** [comment]
> It also added .try_into for the enum variants. The doctest show this by converting a GeoJson to a Result<Feature, _>

I totally missed that. Sorry!

**Comment by rory** [comment]
I have tweaked the dependencies to limit what features, but in my (quicky, unexperienced) testing, it didn't appear to change much.

`thiserror` depends on `thiserror-impl` which depends on `syn`.

**Comment by frewsxcv** [comment]
thanks for the PR @rory. can you speak to what this new dependency offers us functionality wise? adding new dependencies comes at a maintenance and compilation speed cost, and would like to hear more about the benefits of this crate. it looks like we now explicitly implement `TryInto`, but we should have already had access to it with these generic implementations:

https://doc.rust-lang.org/std/convert/trait.TryFrom.html#impl-TryFrom%3CU%3E

https://doc.rust-lang.org/std/convert/trait.TryInto.html#impl-TryInto%3CU%3E

and an example:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3bea4ed96c021450dc19108897822abc

**Comment by rory** [comment]
This patch adds `TryInto<Geometry> for GeoJson` (& `TryInto<Feature>` & `TryInto<FeatureCollection>`), essentially an easy way to "unwrap" the `GeoJson` enum, which did not exist before. It also  changes the `From<Geometry> for GeoJson` (etc) functionality to be created from `derive_more::From`, rather than explicitly coded.

Yes, an additional dependency adds overhead. This new functionality could be manually added with another ~20 lines of code. So it's a trade off of "another dependency, but less code in `geojson` library" vs "no new dependencies, but more verbose source code in the `geosjon` library". It's your choice as maintainers as to which way you to make that trade off.

My motivation was because I wanted a one line way to convert a `GeoJson` enum into a `Feature` (etc) struct, and I didn't think there was a way to do that.

**Comment by frewsxcv** [comment]
> This patch adds `TryInto<Geometry> for GeoJson` (& `TryInto<Feature>` & `TryInto<FeatureCollection>`), essentially an easy way to "unwrap" the `GeoJson` enum, which did not exist before

I understand now, thanks for clarifying this.

> This new functionality could be manually added with another ~20 lines of code. So it's a trade off of "another dependency, but less code in geojson library" vs "no new dependencies"

I'm generally okay with adding dependencies, but in this particular case, my preference is to add the ~20 lines of code. The lines of code we add will likely never be touched again, since these implementations will likely never change. Whereas dependencies require an extra maintenance overhead, and will occasionally need to be audited and upgraded. And in addition to what @urschrei said, syn and quote are non-trivial dependencies to add with regard to compilation speed and library size for this project.

**Comment by rory** [comment]
OK, I'll close this PR and reimplement in that manner

**Comment by rory** [comment]
OK, I'll close this PR and reimplement in that manner

**Pull request closed without merging**
