### PR TITLE
Add TryInto<geo_types::Geometry<T>> for GeoJson

### PR DESCRIPTION
**Pull request by rory**
This makes conversion to a geo_types more ergonomic

### CODE REVIEW

**Review by michaelkirk — APPROVED** [review]
LGTM - I'll merge in a couple days unless someone raises concerns.

**Comment by rory** [comment]
Actually, I've been tweaking this, and rather than implementing `TryInto`, you can do `TryFrom`, which is preferred (right?)

I've made https://github.com/rory/rust-geojson/tree/easily-convert-from-to-geo-types instead, which I think should be merged instead

**Comment by michaelkirk** [comment]
Yeah, TryFrom would be better. Do you want to open a new PR or just force push to this one?

**Comment by rory** [comment]
I've created new PR #145 instead.

**Pull request closed without merging**
