### PR TITLE
use thiserror 2.0.6

### PR DESCRIPTION
**Pull request by jayvdb**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Review by lnicola — APPROVED** [review]
We should probably bump the crate version to 0.25.0

**Comment by michaelkirk** [comment]
> We should probably bump the crate version to 0.25.0

As a matter of process: mark any breaking change as breaking in the changelog, and we'll bump at release time. Otherwise it's harder to keep track of when someone has already bumped.

But in this case - what's the breaking change in our public api?

**Comment by jayvdb** [comment]
`thiserror::Error` doesnt appear in the public API according to https://docs.rs/thiserror/latest/thiserror/index.html , so this probably isnt a breaking change.

**Comment by lnicola** [comment]
Yeah, the expansion output is different, but I don't think it can break any users of the crate.

**Review by michaelkirk — APPROVED** [review]

**Pull request merged**
