### PR TITLE
Upgrade to geo-types 0.7

### PR DESCRIPTION
**Pull request by maxburke**

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]
thank you!

**Comment by michaelkirk** [comment]
Sorry, but would you mind if we merge this one from last week instead? 

https://github.com/georust/geojson/pull/158/files

I think it's a little neater to use the CoordFloat trait.

**Comment by maxburke** [comment]
No issues here; just trying to power through a set of package upgrades.

**Comment by frewsxcv** [comment]
@michaelkirk ugh so sorry, forgot we already had that one! thanks again for the contribution @maxburke

**Comment by michaelkirk** [comment]
No worries, my bad for not merging it after it was approved.

**Pull request closed without merging**
